import { TrackArtwork, User, ProfilePicture, CoverPhoto, Playlist, PlaylistAddedTimestamp, PlaylistArtwork, Access } from "@audius/sdk";
import { ChatOpenAI, ChatOpenAICallOptions } from "@langchain/openai";

export type ComplexityLevel = 'simple' | 'moderate' | 'complex' | string;
export type AudiusData = TrackData | UserData | PlaylistData | PopularTrackData | NoMatchData | null;

export interface QueryClassification {
  type: string;
  isEntityQuery: boolean;
  entityType: 'user' | 'track' | 'playlist' | null;
  entity: string | null;
  complexity: ComplexityLevel;
} 

export interface DatasetSchema {
  id: string;
  category_name: string;
  tool_name: string;
  api_name: string;
  api_description: string;
  required_parameters: DatasetParameters[];
  optional_parameters: DatasetParameters[];
  method: string;
  template_response?: Record<string, any>;
  api_url: string;
  parameters?: Record<string, any>;
  default_parameters?: { [key: string]: any };
}

export interface DatasetParameters {
  name: string;
  type: string;
  description: string;
  default: string;
}

export interface Entity {
  // Define this based on your entities (e.g., UserEntity, TrackEntity, PlaylistEntity)
}

export interface GraphState {
  llm: ChatOpenAI<ChatOpenAICallOptions>; // Essential
  query: string; // Essential
  queryType: QueryType; // Essential
  categories: string[]; // Essential
  apis: DatasetSchema[]; // Essential
  bestApi: DatasetSchema | null; // Optional
  secondaryApi: DatasetSchema | null; // Optional
  params: {
    apiUrl?: string;
    timeframe?: string;
    limit?: number;
    track?: string;
    user?: string;
    artist?: string;
    // Add any other parameters you might need
  }; // Essential
  response: any; // Essential
  secondaryResponse: any | null;  // Optional
  error: boolean; // Essential
  formattedResponse: string | null; // Optional
  message: string | null; // Optional
  isEntityQuery: boolean; // Essential
  entityName: string | null; // Optional
  entity: Entity | null; // Optional (consider revisiting its necessity)
  parameters: { [key: string]: any } | null; // Optional
  complexity: ComplexityLevel; // Essential
  multiStepHandled: boolean; // Optional
  initialState: GraphState | null; // Optional
  entityType: 'user' | 'playlist' | 'track' | null; // Essential
}

export type QueryType =
  | 'trending_tracks'
  | 'search_tracks'
  | 'search_users'
  | 'search_playlists'
  | 'search_genres'
  | 'genre_info'
  | string;

export type TrackData = {
  id: string;
  type: 'track';
  title: string;
  artwork: TrackArtwork;  
  description: string | null;
  genre: string;
  mood: string | null;
  releaseDate: string | null;
  remixOf: TrackData | null;
  repostCount: number;
  favoriteCount: number;
  commentCount: number;
  tags: string[] | null;
  user: User;
  duration: number;
  isDownloadable: boolean;
  playCount: number;
  permalink: string;
  isStreamable: boolean;
};

export type UserData = {
  id: string;
  type: 'user';
  name: string;
  handle: string;
  bio: string | null;
  followerCount: number;
  followeeCount: number;
  trackCount: number;
  playlistCount: number;
  albumCount: number;
  isVerified: boolean;
  profilePicture: ProfilePicture;
  coverPhoto: CoverPhoto;
  twitterHandle: string | null;
  instagramHandle: string | null;
  tiktokHandle: string | null;
  website: string | null;
  location: string | null;
  isDeactivated: boolean;
  isAvailable: boolean;
  supporterCount: number;
  supportingCount: number;
  totalAudioBalance: number;
};

export interface PlaylistData {
  id: string;
  playlistName: string;
  description?: string;
  isAlbum: boolean;
  trackCount: number;
  totalPlayCount: number;
  repostCount: number;
  favoriteCount: number;
  user: User;
  playlistContents: Array<PlaylistAddedTimestamp>;
  artwork?: PlaylistArtwork;
  permalink: string;
  isImageAutogenerated: boolean;
  access: Access;
  ddexApp?: string;
  upc?: string;
  tracks: TrackData[];
}
  
export interface PopularTrackData {
    type: 'popularTrack';
    data: {
      rank: number;
      title: string;
      artist: string;
      playCount: number;
      duration: number;
      genre: string;
      mood?: string;
      releaseDate?: string;
  };
}
  
export interface NoMatchData {
    type: 'noMatch';
    data: {
      searchedTrack: string;
      searchedArtist: string;
    availableTracks: { title: string; artist: string; playCount: number }[];
  };
}

/**
 * Type guard to check if an object is of type UserData.
 * @param entity - The entity to check.
 * @returns True if entity is UserData, else false.
 */
export function isUserData(entity: any): entity is UserData {
  return entity && typeof entity === 'object' && 'name' in entity;
}

/**
 * Type guard to check if an object is of type TrackData.
 * @param entity - The entity to check.
 * @returns True if entity is TrackData, else false.
 */
export function isTrackData(entity: any): entity is TrackData {
  return entity && typeof entity === 'object' && 'title' in entity;
}

/**
 * Type guard to check if an object is of type PlaylistData.
 * @param entity - The entity to check.
 * @returns True if entity is PlaylistData, else false.
 */
export function isPlaylistData(entity: any): entity is PlaylistData {
  return entity && typeof entity === 'object' && 'playlistName' in entity;
}

// Additional helper functions and type definitions...
