import { ChatOpenAI } from '@langchain/openai';
import { TrackArtwork, User, ProfilePicture, CoverPhoto, Playlist, PlaylistAddedTimestamp, PlaylistArtwork, Access, Track } from "@audius/sdk";
import { Messages } from '@langchain/langgraph'

export type ComplexityLevel = 'simple' | 'moderate' | 'complex';


export type QueryCategorization = {
  queryType: QueryType;
  isEntityQuery: boolean;
  entityType: EntityType;
  complexity: ComplexityLevel;
  entityName: string | null;
}

export interface DatasetSchema {
  id: string;
  category_name: string;
  tool_name: string;
  api_name: string;
  api_description: string;
  required_parameters: DatasetParameters[];
  optional_parameters: DatasetParameters[];
  method: string;
  template_response?: Record<string, any>;
  api_url: string;
  parameters?: Record<string, any>;
  default_parameters?: { [key: string]: any };
}

export interface DatasetParameters {
  name: string;
  description: string;
  type: string;    // Must match the type sent to the API
  default: any;    // Default value for the parameter
}

export type ErrorState = {
  code: string;
  message: string;
  suggestion?: string;
  timestamp: number;
  node: string;
}

export interface GraphState {
  llm: ChatOpenAI | null;
  query: string | null;
  queryType: QueryType | null;
  categories: string[] | null;
  apis: DatasetSchema[] | null;
  bestApi: DatasetSchema | null;
  parameters: Record<string, any> | null;
  response: {
    data: Array<TrackData | UserData | PlaylistData>
  } | null;
  complexity: ComplexityLevel | null;
  isEntityQuery: boolean | null;
  entityName: string | null;
  entityType: EntityType | null;
  error: ErrorState | null;
  errorHistory: ErrorState[];
  messages: Messages | null;
  messageHistory: Messages[];
  selectedHost: string | null;
  entity: TrackData | UserData | PlaylistData | null;
  secondaryApi: DatasetSchema | null;
  secondaryResponse: string | null;
  initialState: GraphState | null;
  formattedResponse: string | null;
}

export type QueryType =
  | 'general'
  | 'trending_tracks'
  | 'search'
  | 'entity_stats'
  | 'trending_playlists';

export type EntityType = 'track' | 'user' | 'playlist' | null;

export type TrackData = {
  id: string;
  type: 'track';
  title: string;
  artwork: TrackArtwork;  
  description: string | null;
  genre: string;
  mood: string | null;
  releaseDate: string | null;
  remixOf: TrackData | null;
  repostCount: number;
  favoriteCount: number;
  commentCount: number;
  tags: string[] | null;
  user: User;
  duration: number;
  isDownloadable: boolean;
  playCount: number;
  permalink: string;
  isStreamable: boolean;
};

export type UserData = {
  id: string;
  type: 'user';
  name: string;
  handle: string;
  bio: string | null;
  followerCount: number;
  followeeCount: number;
  trackCount: number;
  playlistCount: number;
  albumCount: number;
  isVerified: boolean;
  profilePicture: ProfilePicture;
  coverPhoto: CoverPhoto;
  twitterHandle: string | null;
  instagramHandle: string | null;
  tiktokHandle: string | null;
  website: string | null;
  location: string | null;
  isDeactivated: boolean;
  isAvailable: boolean;
  supporterCount: number;
  supportingCount: number;
  totalAudioBalance: number;
};

export interface PlaylistData {
  id: string;
  playlistName: string;
  description?: string;
  isAlbum: boolean;
  trackCount: number;
  totalPlayCount: number;
  repostCount: number;
  favoriteCount: number;
  user: User;
  playlistContents: Array<PlaylistAddedTimestamp>;
  artwork?: PlaylistArtwork;
  permalink: string;
  isImageAutogenerated: boolean;
  access: Access;
  ddexApp?: string;
  upc?: string;
  tracks: TrackData[];
}
  
export interface PopularTrackData {
    type: 'popularTrack';
    data: {
      rank: number;
      title: string;
      artist: string;
      playCount: number;
      duration: number;
      genre: string;
      mood?: string;
      releaseDate?: string;
  };
}
  
export interface NoMatchData {
    type: 'noMatch';
    data: {
      searchedTrack: string;
      searchedArtist: string;
    availableTracks: { title: string; artist: string; playCount: number }[];
  };
}
/**
 * Type guard to check if an object is of type UserData.
 * @param entity - The entity to check.
 * @returns True if entity is UserData, else false.
 */
export function isUserData(entity: any): entity is UserData {
  return entity && typeof entity === 'object' && 'name' in entity;
}

/**
 * Type guard to check if an object is of type TrackData.
 * @param entity - The entity to check.
 * @returns True if entity is TrackData, else false.
 */
export function isTrackData(entity: any): entity is TrackData {
  return entity && typeof entity === 'object' && 'title' in entity;
}

/**
 * Type guard to check if an object is of type PlaylistData.
 * @param entity - The entity to check.
 * @returns True if entity is PlaylistData, else false.
 */
export function isPlaylistData(entity: any): entity is PlaylistData {
  return entity && typeof entity === 'object' && 'playlistName' in entity;
}

// Additional helper functions and type definitions...

export const initialGraphState: GraphState = {
  llm: null,
  query: null,
  queryType: null,
  categories: null,
  apis: null,
  bestApi: null,
  secondaryApi: null,
  response: null,
  secondaryResponse: null,  
  error: null as ErrorState | null,
  errorHistory: [],
  formattedResponse: null,
  messages: null,
  messageHistory: [],
  isEntityQuery: false,
  entityName: null,
  entity: null,
  parameters: null,
  complexity: null,
  initialState: null,
  entityType: null,
  selectedHost: null
};

export type NodeNames =
  | '__start__'
  | '__end__'
  | 'extract_category'
  | 'get_apis'
  | 'select_api'
  | 'extract_parameters'
  | 'verify_parameters'
  | 'request_parameters'
  | 'create_fetch_request'

export type StateDefinition = {
  [key in NodeNames]: GraphState;
};

export interface SelectAPIResponse {
  api: DatasetSchema;
  parameters: Record<string, any>;
  error: boolean | null;
}

interface ApiEndpoint {
  id: string;
  category_name: string;
  tool_name: string;
  api_name: string;
  api_description: string;
  required_parameters: Array<{
    name: string;
    type: string;
    description: string;
    default: string;
  }>;
  optional_parameters: Array<{
    name: string;
    type: string;
    description: string;
    default: string;
  }>;
  method: string;
  template_response: {
    data: any; // Adjust this type based on your actual data structure
  };
  api_url: string;
}

export interface AudiusCorpus {
  endpoints: ApiEndpoint[];
}

// Similarly for Track and Playlist...

// Add these type definitions
export type TrackProperty = keyof Track;
export type UserProperty = keyof User;
export type PlaylistProperty = keyof Playlist;

// Type guard functions
export function isTrackProperty(prop: string): prop is TrackProperty {
  return ['playCount', 'repostCount', 'favoriteCount', 'genre'].includes(prop);
}

export function isUserProperty(prop: string): prop is UserProperty {
  return ['followerCount', 'trackCount', 'playlistCount'].includes(prop);
}

export function isPlaylistProperty(prop: string): prop is PlaylistProperty {
  return ['trackCount', 'repostCount', 'favoriteCount'].includes(prop);
}

// Update entity type mapping
export const wordToPropertyMap: Record<string, TrackProperty | UserProperty | PlaylistProperty> = {
  'play': 'playCount',
  'plays': 'playCount',
  'follower': 'followerCount',
  'followers': 'followerCount',
  'song': 'trackCount',
  'songs': 'trackCount',
  'track': 'trackCount',
  'tracks': 'trackCount',
  'genre': 'genre',
  'repost': 'repostCount',
  'reposts': 'repostCount',
  'favorite': 'favoriteCount',
  'favorites': 'favoriteCount'
} as const;



